const products = [
  {
    id: 0,
    name: "Easywipe Baby Wipes",
    price: 29.99,
    instock: 100,
    description: "Wiping has never been easier, try new Easywipes.",
    imgSrc: "./images_and_css/wipes.jpg",
  },
  {
    id: 1,
    name: "Newco Nappies",
    price: 150.99,
    instock: 200,
    description: "Your child will love taking a dump. :)",
    imgSrc: "./images_and_css/dyper.jpg",
  },
  {
    id: 2,
    name: "Bugati Stroller",
    price: 5800.0,
    instock: 10,
    description: "Top speed of 15km per hour",
    imgSrc: "./images_and_css/stroller.jpg",
  },
  {
    id: 3,
    name: "Baby Monitor",
    price: 240.0,
    instock: 10,
    description: "Great for checking on your baby and spying on loved ones",
    imgSrc: "./images_and_css/baby_monitor.png",
  },
  {
    id: 4,
    name: "Baby Cot",
    price: 24999.0,
    instock: 4,
    description: "Prevents future back problems from birth",
    imgSrc: "./images_and_css/cot.jpg",
  },
  {
    id: 5,
    name: "Mobile",
    price: 80.0,
    instock: 40,
    description: "Helps your baby fall asleep...NOT!!! :).",
    imgSrc: "./images_and_css/mobile.jpg",
  },
  {
    id: 6,
    name: "Delivery To Home",
    price: 200.0,
    instock: 1,
    description: "Delivered to your home",
    imgSrc: "./images_and_css/deliveryhome.jpg",
  },
  {
    id: 6,
    name: "Pickup at Store",
    price: 100.0,
    instock: 1,
    description: "Collect at store",
    imgSrc: "./images_and_css/delivery.jpg",
  },
];
